(function(){"use strict";var STORE_KEY="gemVault";var START_CREDITS=1000;var COLS=5;var ROWS=3;var STAKE_STEP=5;var STAKE_MAX=50000;var SPIN_TICK_MS=70;var COL_STOP_BASE=430;var COL_STOP_GAP=190;var SETTLE_DELAY=240;var SYMBOLS=[{key:"jester",name:"Jester",weight:2,pays:null,wild:true,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M12 4l2.4 6.2L20 6.4l-1.5 8.6H5.5L4 6.4l5.6 3.8L12 4z" fill="#7c3aed"/>'+'<circle cx="12" cy="3.8" r="1.4" fill="#ef4444"/>'+'<circle cx="4.3" cy="6.2" r="1.4" fill="#10b981"/>'+'<circle cx="19.7" cy="6.2" r="1.4" fill="#f6c453"/>'+'<rect x="5" y="15.6" width="14" height="3.4" rx="1.7" fill="#a78bfa"/>'+"</svg>"},{key:"crown",name:"Crown",weight:5,pays:[25,75,250],wild:false,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M3 18.4L4.6 7.6l4.3 3.8L12 4.8l3.1 6.6 4.3-3.8L21 18.4H3z" fill="#f6c453"/>'+'<rect x="3.6" y="18.4" width="16.8" height="2.2" rx="1.1" fill="#d99c1f"/>'+'<circle cx="12" cy="14.4" r="1.3" fill="#ef4444"/>'+"</svg>"},{key:"ruby",name:"Ruby",weight:8,pays:[15,40,120],wild:false,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M12 2.8l7.4 5.3-2.7 12.1H7.3L4.6 8.1 12 2.8z" fill="#ef4444"/>'+'<path d="M12 6.4l4 2.9-1.5 6.5h-5L8 9.3l4-2.9z" fill="#fb7185"/>'+"</svg>"},{key:"emerald",name:"Emerald",weight:11,pays:[10,25,75],wild:false,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M7.2 4h9.6L20 7.2v9.6L16.8 20H7.2L4 16.8V7.2L7.2 4z" fill="#10b981"/>'+'<rect x="8.3" y="8.3" width="7.4" height="7.4" fill="#6ee7b7"/>'+"</svg>"},{key:"sapphire",name:"Sapphire",weight:14,pays:[6,16,50],wild:false,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M12 3c4 4.4 6.4 7.5 6.4 10.4a6.4 6.4 0 0 1-12.8 0C5.6 10.5 8 7.4 12 3z" fill="#3b82f6"/>'+'<circle cx="10" cy="13.4" r="2.2" fill="#93c5fd"/>'+"</svg>"},{key:"harp",name:"Harp",weight:17,pays:[4,10,30],wild:false,art:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+'<path d="M6.4 3C5.4 8.8 6 14.4 7.8 19h2.1C8.4 14.2 7.9 8.9 8.7 3H6.4z" fill="#f6c453"/>'+'<path d="M17.6 3c1 5.8 0.4 11.4-1.4 16h-2.1c1.5-4.8 2-10.1 1.2-16h2.3z" fill="#f6c453"/>'+'<path d="M10.6 5.5v11M12 5.5v11M13.4 5.5v11" stroke="#fde68a" stroke-width="0.9" fill="none"/>'+'<rect x="7" y="19" width="10" height="2.1" rx="1" fill="#d99c1f"/>'+"</svg>"}];var TOTAL_WEIGHT=0;for(var w=0;w<SYMBOLS.length;w+=1){TOTAL_WEIGHT+=SYMBOLS[w].weight;}
var LINES=[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]];var LINE_NAMES=["middle row","top row","bottom row","V line","peak line"];var LINE_COLORS=["#10b981","#f6c453","#ef4444","#a78bfa","#38bdf8"];var reelsEl=document.getElementById("gem-reels");var frameEl=document.getElementById("gem-reel-frame");var bankEl=document.getElementById("gem-bank-sum");var refillEl=document.getElementById("gem-refill");var stakeField=document.getElementById("gem-stake-field");var stakeDown=document.getElementById("gem-stake-down");var stakeUp=document.getElementById("gem-stake-up");var spinBtn=document.getElementById("gem-spin");var readoutEl=document.getElementById("gem-readout");var paytableEl=document.getElementById("gem-paytable");if(!reelsEl||!frameEl||!bankEl||!refillEl||!stakeField||!stakeDown||!stakeUp||!spinBtn||!readoutEl||!paytableEl){return;}
var state={credits:loadCredits(),stake:10,spinning:false,grid:[],cells:[],traces:[],timers:[]};function loadCredits(){var raw=null;try{raw=window.localStorage.getItem(STORE_KEY);}catch(err){raw=null;}
if(raw===null||raw===""){return START_CREDITS;}
var value=Number(raw);if(!isFinite(value)||value<0){return START_CREDITS;}
return round2(value);}
function persist(){try{window.localStorage.setItem(STORE_KEY,String(state.credits));}catch(err){return;}}
function paintBank(){bankEl.textContent=fmt(state.credits);}
function round2(value){return Math.round(value*100)/100;}
function fmt(value){var r=round2(value);return r===Math.floor(r)?String(r):r.toFixed(2);}
function setReadout(text,mood){readoutEl.textContent=text;readoutEl.classList.remove("gem-readout-up","gem-readout-down");if(mood==="up"){readoutEl.classList.add("gem-readout-up-ba820ff4");}else if(mood==="down"){readoutEl.classList.add("gem-readout-down-ba820ff4");}}
function drawSymbol(){var roll=Math.random()*TOTAL_WEIGHT;for(var i=0;i<SYMBOLS.length;i+=1){roll-=SYMBOLS[i].weight;if(roll<0){return i;}}
return SYMBOLS.length-1;}
function buildReels(){reelsEl.innerHTML="";state.cells=[];for(var i=0;i<COLS*ROWS;i+=1){var cell=document.createElement("div");cell.className="gem-cell-ba820ff4";var art=document.createElement("span");art.className="gem-cell-art-ba820ff4";art.innerHTML=SYMBOLS[drawSymbol()].art;cell.appendChild(art);reelsEl.appendChild(cell);state.cells.push(cell);}}
function buildOverlay(){var ns="http://www.w3.org/2000/svg";var svg=document.createElementNS(ns,"svg");svg.setAttribute("class","gem-lines");svg.setAttribute("viewBox","0 0 500 300");svg.setAttribute("preserveAspectRatio","none");svg.setAttribute("aria-hidden","true");state.traces=[];for(var li=0;li<LINES.length;li+=1){var pts=[];for(var c=0;c<COLS;c+=1){pts.push((c*100+50)+","+(LINES[li][c]*100+50));}
var poly=document.createElementNS(ns,"polyline");poly.setAttribute("class","gem-trace");poly.setAttribute("points",pts.join(" "));poly.setAttribute("fill","none");poly.setAttribute("stroke",LINE_COLORS[li]);poly.setAttribute("stroke-width","4");poly.setAttribute("stroke-linecap","round");poly.setAttribute("stroke-linejoin","round");poly.setAttribute("vector-effect","non-scaling-stroke");svg.appendChild(poly);state.traces.push(poly);}
frameEl.appendChild(svg);}
function buildPaytable(){paytableEl.innerHTML="";for(var i=0;i<SYMBOLS.length;i+=1){var sym=SYMBOLS[i];var row=document.createElement("div");row.className="gem-pay-row-ba820ff4";var art=document.createElement("span");art.className="gem-pay-art-ba820ff4";art.innerHTML=sym.art;var name=document.createElement("span");name.className="gem-pay-name-ba820ff4";name.textContent=sym.name;var vals=document.createElement("span");vals.className="gem-pay-vals-ba820ff4";if(sym.pays){vals.textContent="×3 "+sym.pays[0]+" · ×4 "+sym.pays[1]+" · ×5 "+sym.pays[2];}else{vals.textContent="stands in for every paying symbol";}
row.appendChild(art);row.appendChild(name);row.appendChild(vals);paytableEl.appendChild(row);}}
function readStake(){var value=Math.floor(Number(stakeField.value));return isFinite(value)?value:0;}
function clampStake(){var value=readStake();if(value<1){value=1;}
if(value>STAKE_MAX){value=STAKE_MAX;}
stakeField.value=String(value);}
function nudgeStake(delta){if(state.spinning){return;}
var value=readStake()+delta;if(value<1){value=1;}
if(value>STAKE_MAX){value=STAKE_MAX;}
stakeField.value=String(value);}
function lockConsole(locked){spinBtn.disabled=locked;refillEl.disabled=locked;stakeField.disabled=locked;stakeDown.disabled=locked;stakeUp.disabled=locked;}
function clearDecor(){var i;for(i=0;i<state.traces.length;i+=1){state.traces[i].classList.remove("gem-trace-lit-ba820ff4");}
for(i=0;i<state.cells.length;i+=1){state.cells[i].classList.remove("gem-cell-hit","gem-cell-set");}}
function setCellArt(index,symIndex){var art=state.cells[index].firstChild;if(art){art.innerHTML=SYMBOLS[symIndex].art;}}
function spin(){if(state.spinning){return;}
clampStake();var stake=readStake();if(stake<1){setReadout("The minimum stake is 1 credit.","down");return;}
if(stake>state.credits){setReadout("That stake is heavier than your purse.","down");return;}
state.credits=round2(state.credits-stake);persist();paintBank();state.stake=stake;state.spinning=true;state.timers=[];lockConsole(true);clearDecor();state.grid=[];for(var i=0;i<COLS*ROWS;i+=1){state.grid.push(drawSymbol());}
setReadout("The reels are turning…","");for(var c=0;c<COLS;c+=1){rollColumn(c);}}
function rollColumn(col){var indexes=[col,col+COLS,col+COLS*2];var i;for(i=0;i<indexes.length;i+=1){state.cells[indexes[i]].classList.add("gem-cell-blur-ba820ff4");}
var ticker=window.setInterval(function(){for(var k=0;k<indexes.length;k+=1){setCellArt(indexes[k],drawSymbol());}},SPIN_TICK_MS);state.timers.push(ticker);window.setTimeout(function(){window.clearInterval(ticker);for(var k=0;k<indexes.length;k+=1){setCellArt(indexes[k],state.grid[indexes[k]]);state.cells[indexes[k]].classList.remove("gem-cell-blur-ba820ff4");state.cells[indexes[k]].classList.add("gem-cell-set-ba820ff4");}
if(col===COLS-1){window.setTimeout(settle,SETTLE_DELAY);}},COL_STOP_BASE+col*COL_STOP_GAP);}
function bestOnLine(rows,lineBet){var best=null;for(var s=0;s<SYMBOLS.length;s+=1){var candidate=SYMBOLS[s];if(candidate.wild){continue;}
var run=0;for(var c=0;c<COLS;c+=1){var held=SYMBOLS[state.grid[rows[c]*COLS+c]];if(held.wild||held.key===candidate.key){run+=1;}else{break;}}
if(run>=3){var amount=round2(lineBet*candidate.pays[run-3]);if(!best||amount>best.amount){best={amount:amount,run:run,name:candidate.name};}}}
return best;}
function settle(){var lineBet=state.stake/LINES.length;var hits=[];var total=0;for(var li=0;li<LINES.length;li+=1){var hit=bestOnLine(LINES[li],lineBet);if(hit){hit.line=li;hits.push(hit);total+=hit.amount;}}
total=round2(total);if(total>0){state.credits=round2(state.credits+total);persist();paintBank();for(var h=0;h<hits.length;h+=1){state.traces[hits[h].line].classList.add("gem-trace-lit-ba820ff4");for(var c=0;c<hits[h].run;c+=1){var idx=LINES[hits[h].line][c]*COLS+c;state.cells[idx].classList.add("gem-cell-hit-ba820ff4");}}
if(hits.length===1){setReadout(hits[0].name+" ×"+hits[0].run+" on the "+LINE_NAMES[hits[0].line]+" pays "+fmt(total)+".","up");}else{setReadout(hits.length+" lines light up for "+
fmt(total)+" credits!","up");}}else{setReadout("No line this time — the jester keeps "+"his jewels.","");}
state.spinning=false;lockConsole(false);if(state.credits<1){setReadout("The purse is empty — tap Refill to restock "+"the demo credits.","down");}}
function refill(){if(state.spinning){return;}
state.credits=START_CREDITS;persist();paintBank();setReadout("Demo purse restocked to "+START_CREDITS+".","");}
spinBtn.addEventListener("click",spin);refillEl.addEventListener("click",refill);stakeDown.addEventListener("click",function(){nudgeStake(-STAKE_STEP);});stakeUp.addEventListener("click",function(){nudgeStake(STAKE_STEP);});stakeField.addEventListener("change",clampStake);buildReels();buildOverlay();buildPaytable();paintBank();if(state.credits<1){setReadout("The purse is empty — tap Refill to restock "+"the demo credits.","");}})();